service: serverless-csp-reports-ui

plugins:
  - serverless-s3-deploy

resources:
  Resources:
    ClianzCspReports:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: clianz-csp-reports
        AccessControl: PublicRead
        WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: index.html

custom:
  assets:
    targets:
      - bucket: clianz-csp-reports
        files:
          - source: dist/
            globs:
              - '**/*.js'
              - '**/*.map'
              - '**/*.html'

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource:
        - 'arn:aws:s3:::ClianzCspReports/*'