service: serverless-csp-reports

plugins:
  - serverless-s3-deploy

# custom:
#   assets:
#     targets:
#       - bucket: clianz-csp-reports
#         files:
#         - source: dist/
#           globs:
#             - '**/*.html'
#             - '**/*.js'
#             - '**/*.map'


resources:
  Resources:
    ClianzCspReports:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: clianz-csp-reports
        AccessControl: PublicRead
        WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: index.html

custom:
  assets:
    # resolveReferences: false
    targets:
      - bucket: #ClianzCspReports
          Ref: ClianzCspReports
        files:
          - source: dist/
            globs:
              - '**/*.js'
              - '**/*.map'
              - '**/*.html'

# custom:
#   assets:
#     targets:
#       - bucket:
#           Ref: ClianzCspReports
#         files:
#           - source: dist/


# resources:
#   Resources:
#     S3TranscriptionBucket:
#       Type: 'AWS::S3::Bucket'
#       Properties:
#         BucketName: clianz-csp-reports

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource:
        - 'arn:aws:s3:::ClianzCspReports/*'